version: "3.7"

services:
#  postgres:
#    image: postgres:10.5-alpine
#    volumes:
#    - db-data:/var/lib/postgresql/data
#    - ./db/schema:/db/schema

  server:
    build: .
    ports:
    - 3010:3010
    volumes:
    - ./dist:/dist