version: "3.7"

services:
  postgres:
    image: postgres
#    restart: always
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./db/schema:/db/schema
  server:
    build: .
#    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/github.com/yuetsh/Hackathon2018
    depends_on:
    - postgres

volumes:
  db-data: