version: "3.7"

services:
  db:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_DB=hackathon_prod
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./db/schema:/db/schema
    ports:
    - "5432:5432"
    restart: unless-stopped

  api:
    build: .
    ports:
    - 3010:3010
    volumes:
    - ./dist:/opt/api/dist
    - ./templates:/opt/api/templates
    links:
    - db
    depends_on:
    - db

  proxy:
    build:
      context:  ./nginx
    ports:
    - 443:443
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/opt/ssl/certs/api.yueyue.work.pem:/etc/nginx/certs/api.yueyue.work.pem
    - /etc/opt/ssl/private/api.yueyue.work.key:/etc/nginx/certs/api.yueyue.work.key
    links:
    - api

volumes:
  db-data: