version: "3.7"

services:
#  postgres:
#    image: postgres:10.5-alpine
#    volumes:
#    - db-data:/var/lib/postgresql/data
#    - ./db/schema:/db/schema

#  ffmpeg:
#    image: jrottenberg/ffmpeg:3.4-alpine

  server:
    build: .
    ports:
    - 3010:3010
    volumes:
    - .:/go/src/github.com/yuetsh/Hackathon2018_API