version: "3.6"

services:
  db:
    image: postgres:10.5-alpine
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
    - ../db/schema:/db/schema

  api:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    environment:
    - POSTGRES_DB=${POSTGRES_DB_DEV}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - ENV=dev
    ports:
    - 3010:3010
    volumes:
    - ..:/go/src/github.com/yuetsh/Hackathon2018_API
    links:
    - db
    depends_on:
    - db

volumes:
  db-data: